title: "Dev Log - Andre Sampaio"
description: "Atualizações automáticas dos meus projetos de desenvolvimento"
url: "https://AndreMicael.github.io"
baseurl: "/blog-eucomittei"
author:
  name: "Andre Sampaio"

theme: minima

plugins:
  - jekyll-feed

show_excerpts: true

minima:
  date_format: "%d/%m/%Y"
